### ISSUE TITLE
What are current applications of GenAI (and how could we use it but that’s a follow-up)

### ISSUE THREAD

**Issue by markspolakovs** [2023-gpig-a/issues#4]

**Comment by BabarKhanDev** [comment]
I made this UML diagram for the AI process that we use
https://lucid.app/lucidchart/3df7583f-e8b7-47d7-a63e-c2394dc01c0b/edit?viewport_loc=-2146%2C-540%2C2674%2C1304%2C0_0&invitationId=inv_617b8b5f-caba-4f8a-a6f6-b2e0ade569af
